name: Deploy to VPS via SSH

on:
  push:
    branches:
      - master  # Ganti jika branch kamu berbeda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_github
          chmod 600 ~/.ssh/id_rsa_github
          ssh-keyscan -p 2354 -H 103.235.75.42 >> ~/.ssh/known_hosts

      - name: Debug SSH folder (optional)
        run: |
          ls -lah ~/.ssh
          head -n 5 ~/.ssh/id_rsa_github

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa_github -o StrictHostKeyChecking=no trifipor@103.235.75.42 -p 2354 << 'EOF'
            cd /home/trifipor/cicd/test-react
            git pull origin master
            docker compose build
            docker compose up -d
          EOF
